/home/csguest/Frosk/prgm/echo/obj/main.c.o: \
 /home/csguest/Frosk/prgm/echo/src/main.c \
 /home/csguest/Frosk/include/prgm/frosk.h \
 /home/csguest/Frosk/include/prgm/types.h \
 /home/csguest/Frosk/include/prgm/stddef.h \
 /home/csguest/Frosk/include/prgm/frosk/def.h \
 /home/csguest/Frosk/include/prgm/frosk/devtype.h \
 /home/csguest/Frosk/include/prgm/util.h

/home/csguest/Frosk/include/prgm/frosk.h:

/home/csguest/Frosk/include/prgm/types.h:

/home/csguest/Frosk/include/prgm/stddef.h:

/home/csguest/Frosk/include/prgm/frosk/def.h:

/home/csguest/Frosk/include/prgm/frosk/devtype.h:

/home/csguest/Frosk/include/prgm/util.h:
